packages:
  - "apps/*"
  - "packages/*"
  - "modules/*"

allowBuilds:
  "@biomejs/biome": true
  cpu-features: set this to true or false
  "es5-ext": true
  "esbuild": true
  protobufjs: true
  "sharp": true
  ssh2: set this to true or false
