ALTER TABLE "account_teams" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "account_teams" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "accounts" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "accounts" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "audit_logs" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "audit_logs" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "campaign_influence" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "campaign_influence" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "campaign_members" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "campaign_members" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "campaigns" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "campaigns" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "commissions" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "commissions" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "contact_consent_preferences" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "contact_consent_preferences" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "contacts" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "contacts" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "contracts" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "contracts" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "currencies" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "currencies" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "document_templates" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "document_templates" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "email_bounce_events" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "email_bounce_events" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "email_calendar_sync_runs" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "email_calendar_sync_runs" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "email_calendar_sync_settings" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "email_calendar_sync_settings" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "email_click_events" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "email_click_events" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "email_open_events" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "email_open_events" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "email_read_time_events" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "email_read_time_events" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "email_reply_events" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "email_reply_events" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "email_templates" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "email_templates" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "email_trackers" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "email_trackers" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "email_unsubscribes" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "email_unsubscribes" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "esignature_requests" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "esignature_requests" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "field_definitions" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "field_definitions" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "forecast_adjustments" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "forecast_adjustments" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "invoices" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "invoices" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "kb_articles" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "kb_articles" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "kb_categories" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "kb_categories" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "layout_definitions" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "layout_definitions" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "lead_assignment_rule_entries" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "lead_assignment_rule_entries" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "lead_assignment_rules" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "lead_assignment_rules" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "lead_auto_conversion_rules" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "lead_auto_conversion_rules" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "lead_conversion_mappings" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "lead_conversion_mappings" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "lead_scoring_rules" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "lead_scoring_rules" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "lead_sla_targets" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "lead_sla_targets" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "lead_sla_trackers" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "lead_sla_trackers" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "leads" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "leads" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "marketing_segments" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "marketing_segments" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "marketing_sequence_ab_allocations" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "marketing_sequence_ab_allocations" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "marketing_sequence_caps" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "marketing_sequence_caps" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "marketing_sequence_conversions" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "marketing_sequence_conversions" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "marketing_sequence_exclusions" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "marketing_sequence_exclusions" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "marketing_sequence_exit_triggers" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "marketing_sequence_exit_triggers" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "marketing_sequence_folders" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "marketing_sequence_folders" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "marketing_sequence_global_variables" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "marketing_sequence_global_variables" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "marketing_sequence_goals" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "marketing_sequence_goals" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "marketing_sequence_link_actions" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "marketing_sequence_link_actions" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "marketing_sequence_memberships" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "marketing_sequence_memberships" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "marketing_sequence_open_actions" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "marketing_sequence_open_actions" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "marketing_sequence_reply_actions" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "marketing_sequence_reply_actions" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "marketing_sequence_step_branches" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "marketing_sequence_step_branches" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "marketing_sequence_step_split_tests" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "marketing_sequence_step_split_tests" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "marketing_sequence_steps" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "marketing_sequence_steps" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "marketing_sequence_suppressions" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "marketing_sequence_suppressions" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "marketing_sequence_tag_mappings" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "marketing_sequence_tag_mappings" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "marketing_sequence_tags" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "marketing_sequence_tags" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "marketing_sequences" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "marketing_sequences" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "memberships" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "memberships" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "merged_documents" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "merged_documents" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "opportunities" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "opportunities" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "opportunity_approval_steps" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "opportunity_approval_steps" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "opportunity_approvals" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "opportunity_approvals" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "opportunity_competitors" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "opportunity_competitors" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "opportunity_product_schedules" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "opportunity_product_schedules" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "opportunity_products" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "opportunity_products" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "opportunity_splits" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "opportunity_splits" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "opportunity_stage_duration_rules" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "opportunity_stage_duration_rules" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "opportunity_stage_gates" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "opportunity_stage_gates" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "opportunity_stage_history" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "opportunity_stage_history" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "opportunity_teams" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "opportunity_teams" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "picklist_dependencies" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "picklist_dependencies" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "pricebook_entries" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "pricebook_entries" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "pricebooks" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "pricebooks" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "products" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "products" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "quotas" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "quotas" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "reports" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "reports" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "roles" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "roles" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "scheduled_report_runs" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "scheduled_report_runs" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "scheduled_reports" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "scheduled_reports" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "schema_migrations" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "schema_migrations" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "sla_policies" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "sla_policies" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "stage_forecast_mappings" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "stage_forecast_mappings" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "stage_guidance" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "stage_guidance" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "stage_probabilities" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "stage_probabilities" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "subscriptions" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "subscriptions" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "survey_responses" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "survey_responses" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "surveys" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "surveys" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "territories" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "territories" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "territory_members" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "territory_members" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "ticket_assignment_rule_entries" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "ticket_assignment_rule_entries" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "ticket_assignment_rules" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "ticket_assignment_rules" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "ticket_comments" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "ticket_comments" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "ticket_escalation_rules" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "ticket_escalation_rules" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "ticket_escalations" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "ticket_escalations" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "ticket_macros" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "ticket_macros" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "ticket_milestones" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "ticket_milestones" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "ticket_tag_links" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "ticket_tag_links" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "ticket_tags" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "ticket_tags" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "tickets" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "tickets" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "validation_rules" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "validation_rules" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "webhook_deliveries" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "webhook_deliveries" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "webhook_dlq" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "webhook_dlq" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "webhook_outbox" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "webhook_outbox" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "webhooks" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "webhooks" USING ("org_id" = current_setting('app.current_org_id', true));
ALTER TABLE "workflows" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tenant_isolation" ON "workflows" USING ("org_id" = current_setting('app.current_org_id', true));
